#!/usr/bin/make -f
# $Id: Makefile 6299 2008-10-31 01:09:11Z clworld $

# options
B25      = -DB25
TRACE    = -rdynamic -DTRACE

ifdef B25
  B25_PATH = ../arib25v025/arib25/src
  B25_CLEAN = clean_b25
  B25_OBJS = B25Decoder.o
  B25_OBJS_EXT = $(B25_PATH)/arib_std_b25.o $(B25_PATH)/b_cas_card.o $(B25_PATH)/multi2.o $(B25_PATH)/ts_section_parser.o
  PCSC_LDLIBS ?= `pkg-config libpcsclite --libs`
  B25_LIBS = $(PCSC_LDLIBS) -lm
endif
ifdef TRACE
  TRACE_LIB = -lbfd
endif

DIST     = .
CXX      = g++
CXXFLAGS =	-O2 -g -Wall -pthread -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 $(B25) $(TRACE) `pkg-config --cflags glib-2.0`
LDFLAGS  = -pthread

OBJS   = recfriio.o error.o usbops.o IoThread.o Recordable.o AbstractFriio.o FriioWhite.o FriioBlack.o $(B25_OBJS)
LIBS   = -lboost_thread-mt -lboost_filesystem `pkg-config --libs glib-2.0` $(TRACE_LIB)
TARGET = $(DIST)/recfriio

all: $(TARGET)

clean: $(B25_CLEAN)
	rm -f $(OBJS) $(TARGET)

ifdef B25
clean_b25:
	cd $(B25_PATH); make clean
endif

$(TARGET):	$(OBJS) $(B25_OBJS_EXT)
	$(CXX) $(LDFLAGS) -o $(TARGET) $(OBJS) $(B25_OBJS_EXT) $(B25_LIBS) $(LIBS)

depend:
	$(CXX) -MM $(OBJS:.o=.cpp) > Makefile.dep

# B25_OBJS_EXT
$(B25_PATH)/arib_std_b25.o:
	cd $(B25_PATH); make all
$(B25_PATH)/b_cas_card.o:
	cd $(B25_PATH); make all
$(B25_PATH)/multi2.o:
	cd $(B25_PATH); make all
$(B25_PATH)/ts_section_parser.o:
	cd $(B25_PATH); make all

-include Makefile.dep
