recfriio.o: recfriio.cpp setting.hpp error.hpp Recordable.hpp
usbops.o: usbops.cpp usbops.hpp error.hpp AutoCloser.hpp
error.o: error.cpp error.hpp
IoThread.o: IoThread.cpp usbops.hpp error.hpp RingBuf.hpp IoThread.hpp \
 setting.hpp
Recordable.o: Recordable.cpp FriioWhite.hpp Recordable.hpp \
 AbstractFriio.hpp setting.hpp error.hpp RingBuf.hpp IoThread.hpp \
 usbops.hpp FriioBlack.hpp
AbstractFriio.o: AbstractFriio.cpp usbops.hpp error.hpp AutoCloser.hpp \
 AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp Recordable.hpp
FriioWhite.o: FriioWhite.cpp usbops.hpp error.hpp FriioWhite.hpp \
 Recordable.hpp AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp
FriioBlack.o: FriioBlack.cpp usbops.hpp error.hpp FriioBlack.hpp \
 Recordable.hpp AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp
B25Decoder.o: B25Decoder.cpp ../arib25v025/arib25/src/arib_std_b25.h \
 ../arib25v025/arib25/src/portable.h \
 ../arib25v025/arib25/src/b_cas_card.h \
 ../arib25v025/arib25/src/b_cas_card.h B25Decoder.hpp error.hpp
Hdus.o: Hdus.cpp usbops.hpp error.hpp Hdus.hpp Recordable.hpp \
  AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp decrypt.c
Hdp.o: Hdp.cpp usbops.hpp error.hpp Hdp.hpp Recordable.hpp \
  AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp decrypt.c
Udp.o: Udp.cpp Udp.hpp
